name: Java CI

on:
  push:
    paths:
      - '**.gradle'
      - '**.properties'
      - '**.yml'
      - '**.json'
      - '**/src/**'
    branches:
      - "1.16"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Upload to Maven
        run: ./gradlew build publish --stacktrace
        if: |
          !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.pull_request.title, '[ci skip]')
        env:
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
